# Generated by Django 6.0.6 on 2026-08-13 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0048_series_dependencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(
                fields=[
                    'project',
                    'archived',
                    'state',
                    '-date',
                    'delegate',
                    'submitter',
                ],
                name='patch_covering_idx_default',
            ),
        ),
    ]
