# Generated by Django 6.0.7 on 2026-07-31 21:26

import django.db.models.deletion
import patchwork.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0048_series_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='The label value.', max_length=25
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='A description of what the label is and when it should be applied.',
                        null=True,
                    ),
                ),
                (
                    'color',
                    patchwork.fields.ColorField(
                        help_text='The color code to use in the UI.'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        help_text='The project this label is associated with. If unset, this label is global to the instance',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='labels',
                        related_query_name='label',
                        to='patchwork.project',
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cover',
            name='labels',
            field=models.ManyToManyField(to='patchwork.label'),
        ),
        migrations.AddField(
            model_name='patch',
            name='labels',
            field=models.ManyToManyField(to='patchwork.label'),
        ),
    ]
