# Generated by Django 6.0.6 on 2026-07-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0049_add_patch_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='labels',
            field=models.ManyToManyField(to='patchwork.label'),
        ),
        migrations.AddField(
            model_name='cover',
            name='labels_cache',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patch',
            name='labels_cache',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='label',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this label is associated with. If unset, this label is global to the instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', related_query_name='label', to='patchwork.project'),
        ),
    ]
