# Generated by Django 6.0.6 on 2026-07-11 08:18

import patchwork.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0050_cover_labels_series_labels_alter_label_project'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='cover',
        #    name='labels',
        #),
        #migrations.RemoveField(
        #    model_name='patch',
        #    name='labels',
        #),
        #migrations.RemoveField(
        #    model_name='series',
        #    name='labels',
        #),
        migrations.AddField(
            model_name='cover',
            name='labels',
            field=patchwork.fields.LabelsField(default=''),
        ),
        migrations.AddField(
            model_name='patch',
            name='labels',
            field=patchwork.fields.LabelsField(default=''),
        ),
        migrations.AddField(
            model_name='series',
            name='labels',
            field=patchwork.fields.LabelsField(default=''),
        ),
    ]
